// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.3
// Project name: SquareLine_Project

#include "../ui.h"

void ui_scrMeasure_screen_init(void)
{
    ui_scrMeasure = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_scrMeasure, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM);      /// Flags
    lv_obj_set_flex_flow(ui_scrMeasure, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_scrMeasure, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_set_style_bg_color(ui_scrMeasure, lv_color_hex(0xDCD4D4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrMeasure, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_scrMeasure, lv_color_hex(0x6F6262), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_scrMeasure, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_scrMeasure, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_scrMeasure, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_scrMeasure, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_scrMeasure, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_scrMeasure, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_scrMeasure, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_scrMeasure, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_scrMeasure, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabView3 = lv_tabview_create(ui_scrMeasure, LV_DIR_TOP, 50);
    lv_obj_set_width(ui_TabView3, lv_pct(100));
    lv_obj_set_height(ui_TabView3, lv_pct(100));
    lv_obj_clear_flag(ui_TabView3, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_TabView3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TabView3, lv_color_hex(0x706D6D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TabView3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_TabView3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TabView3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TabView3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TabView3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_TabView3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_TabView3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TabView3, &ui_font_malgun14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_pad_left(lv_tabview_get_tab_btns(ui_TabView3), 0,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(lv_tabview_get_tab_btns(ui_TabView3), 0,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(lv_tabview_get_tab_btns(ui_TabView3), 0,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(lv_tabview_get_tab_btns(ui_TabView3), 0,  LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_tabview_get_tab_btns(ui_TabView3), &ui_font_malgun20,  LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(lv_tabview_get_tab_btns(ui_TabView3), 0,  LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_TabView3), lv_color_hex(0xB0ACAC),
                              LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_TabView3), 255,  LV_PART_ITEMS | LV_STATE_DEFAULT);

    ui_TapPage2 = lv_tabview_add_tab(ui_TabView3, "MEASURE");
    lv_obj_set_flex_flow(ui_TapPage2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_TapPage2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_pad_left(ui_TapPage2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TapPage2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TapPage2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TapPage2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TapPage2, &ui_font_malgun14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container6 = lv_obj_create(ui_TapPage2);
    lv_obj_remove_style_all(ui_Container6);
    lv_obj_set_width(ui_Container6, lv_pct(100));
    lv_obj_set_height(ui_Container6, lv_pct(78));
    lv_obj_set_align(ui_Container6, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container6, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Container6, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_SPACE_EVENLY);
    lv_obj_clear_flag(ui_Container6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Container6, lv_color_hex(0xF8F4F4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container6, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Container6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Container6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel26 = lv_obj_create(ui_Container6);
    lv_obj_set_width(ui_Panel26, lv_pct(48));
    lv_obj_set_height(ui_Panel26, LV_SIZE_CONTENT);    /// 10
    lv_obj_set_x(ui_Panel26, -320);
    lv_obj_set_y(ui_Panel26, -152);
    lv_obj_set_align(ui_Panel26, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel26, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel26, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel26, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel26, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel26, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel26, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel26, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel26, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel26, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel26, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel26, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Panel26, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Panel26, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label42 = lv_label_create(ui_Panel26);
    lv_obj_set_height(ui_Label42, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_flex_grow(ui_Label42, 1);
    lv_obj_set_align(ui_Label42, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label42, _("input_volt_rms"));
    lv_label_set_recolor(ui_Label42, "true");
    lv_obj_set_style_text_font(ui_Label42, &ui_font_malgun20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblInputVoltRms = lv_label_create(ui_Panel26);
    lv_obj_set_width(ui_lblInputVoltRms, 50);
    lv_obj_set_height(ui_lblInputVoltRms, LV_SIZE_CONTENT);    /// 55
    lv_obj_set_align(ui_lblInputVoltRms, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblInputVoltRms, _("250"));
    lv_label_set_recolor(ui_lblInputVoltRms, "true");
    lv_obj_set_style_text_color(ui_lblInputVoltRms, lv_color_hex(0x1B15C6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblInputVoltRms, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblInputVoltRms, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblInputVoltRms, &ui_font_malgun20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblInputVoltRms, lv_color_hex(0xE6F0CF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblInputVoltRms, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel29 = lv_obj_create(ui_Container6);
    lv_obj_set_width(ui_Panel29, lv_pct(48));
    lv_obj_set_height(ui_Panel29, LV_SIZE_CONTENT);    /// 10
    lv_obj_set_x(ui_Panel29, -320);
    lv_obj_set_y(ui_Panel29, -152);
    lv_obj_set_align(ui_Panel29, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel29, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel29, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel29, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel29, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel29, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel29, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel29, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel29, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel29, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel29, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel29, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Panel29, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Panel29, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label44 = lv_label_create(ui_Panel29);
    lv_obj_set_height(ui_Label44, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_flex_grow(ui_Label44, 1);
    lv_obj_set_align(ui_Label44, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label44, _("input_curr_rms"));
    lv_label_set_recolor(ui_Label44, "true");
    lv_obj_set_style_text_font(ui_Label44, &ui_font_malgun20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Label44, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label44, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label44, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblInputCurrRms = lv_label_create(ui_Panel29);
    lv_obj_set_width(ui_lblInputCurrRms, 50);
    lv_obj_set_height(ui_lblInputCurrRms, LV_SIZE_CONTENT);    /// 55
    lv_obj_set_align(ui_lblInputCurrRms, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblInputCurrRms, _("250"));
    lv_label_set_recolor(ui_lblInputCurrRms, "true");
    lv_obj_set_style_text_color(ui_lblInputCurrRms, lv_color_hex(0x1B15C6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblInputCurrRms, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblInputCurrRms, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblInputCurrRms, &ui_font_malgun20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblInputCurrRms, lv_color_hex(0xE6F0CF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblInputCurrRms, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel48 = lv_obj_create(ui_Container6);
    lv_obj_set_width(ui_Panel48, lv_pct(48));
    lv_obj_set_height(ui_Panel48, LV_SIZE_CONTENT);    /// 10
    lv_obj_set_x(ui_Panel48, -320);
    lv_obj_set_y(ui_Panel48, -152);
    lv_obj_set_align(ui_Panel48, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel48, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel48, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel48, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel48, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel48, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel48, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel48, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel48, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel48, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel48, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel48, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Panel48, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Panel48, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label46 = lv_label_create(ui_Panel48);
    lv_obj_set_height(ui_Label46, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_flex_grow(ui_Label46, 1);
    lv_obj_set_align(ui_Label46, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label46, _("vdc_link_volt_rms"));
    lv_label_set_recolor(ui_Label46, "true");
    lv_obj_set_style_text_font(ui_Label46, &ui_font_malgun20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Label46, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label46, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label46, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblVdcLinkVoltRms = lv_label_create(ui_Panel48);
    lv_obj_set_width(ui_lblVdcLinkVoltRms, 50);
    lv_obj_set_height(ui_lblVdcLinkVoltRms, LV_SIZE_CONTENT);    /// 55
    lv_obj_set_align(ui_lblVdcLinkVoltRms, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblVdcLinkVoltRms, _("250"));
    lv_label_set_recolor(ui_lblVdcLinkVoltRms, "true");
    lv_obj_set_style_text_color(ui_lblVdcLinkVoltRms, lv_color_hex(0x1B15C6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblVdcLinkVoltRms, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblVdcLinkVoltRms, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblVdcLinkVoltRms, &ui_font_malgun20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblVdcLinkVoltRms, lv_color_hex(0xE6F0CF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblVdcLinkVoltRms, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel49 = lv_obj_create(ui_Container6);
    lv_obj_set_width(ui_Panel49, lv_pct(48));
    lv_obj_set_height(ui_Panel49, LV_SIZE_CONTENT);    /// 10
    lv_obj_set_x(ui_Panel49, -320);
    lv_obj_set_y(ui_Panel49, -152);
    lv_obj_set_align(ui_Panel49, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel49, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel49, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel49, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel49, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel49, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel49, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel49, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel49, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel49, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel49, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel49, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Panel49, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Panel49, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label49 = lv_label_create(ui_Panel49);
    lv_obj_set_height(ui_Label49, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_flex_grow(ui_Label49, 1);
    lv_obj_set_align(ui_Label49, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label49, _("bat_volt_rms"));
    lv_label_set_recolor(ui_Label49, "true");
    lv_obj_set_style_text_font(ui_Label49, &ui_font_malgun20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Label49, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label49, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label49, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblBatVoltRms = lv_label_create(ui_Panel49);
    lv_obj_set_width(ui_lblBatVoltRms, 50);
    lv_obj_set_height(ui_lblBatVoltRms, LV_SIZE_CONTENT);    /// 55
    lv_obj_set_align(ui_lblBatVoltRms, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblBatVoltRms, _("250"));
    lv_label_set_recolor(ui_lblBatVoltRms, "true");
    lv_obj_set_style_text_color(ui_lblBatVoltRms, lv_color_hex(0x1B15C6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblBatVoltRms, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblBatVoltRms, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblBatVoltRms, &ui_font_malgun20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblBatVoltRms, lv_color_hex(0xE6F0CF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblBatVoltRms, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel50 = lv_obj_create(ui_Container6);
    lv_obj_set_width(ui_Panel50, lv_pct(48));
    lv_obj_set_height(ui_Panel50, LV_SIZE_CONTENT);    /// 10
    lv_obj_set_x(ui_Panel50, -320);
    lv_obj_set_y(ui_Panel50, -152);
    lv_obj_set_align(ui_Panel50, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel50, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel50, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel50, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel50, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel50, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel50, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel50, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel50, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel50, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel50, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel50, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Panel50, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Panel50, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label50 = lv_label_create(ui_Panel50);
    lv_obj_set_height(ui_Label50, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_flex_grow(ui_Label50, 1);
    lv_obj_set_align(ui_Label50, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label50, _("bat_current_rms"));
    lv_label_set_recolor(ui_Label50, "true");
    lv_obj_set_style_text_font(ui_Label50, &ui_font_malgun20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Label50, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label50, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label50, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblBatCurrentRms = lv_label_create(ui_Panel50);
    lv_obj_set_width(ui_lblBatCurrentRms, 50);
    lv_obj_set_height(ui_lblBatCurrentRms, LV_SIZE_CONTENT);    /// 55
    lv_obj_set_align(ui_lblBatCurrentRms, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblBatCurrentRms, _("250"));
    lv_label_set_recolor(ui_lblBatCurrentRms, "true");
    lv_obj_set_style_text_color(ui_lblBatCurrentRms, lv_color_hex(0x1B15C6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblBatCurrentRms, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblBatCurrentRms, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblBatCurrentRms, &ui_font_malgun20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblBatCurrentRms, lv_color_hex(0xE6F0CF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblBatCurrentRms, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel51 = lv_obj_create(ui_Container6);
    lv_obj_set_width(ui_Panel51, lv_pct(48));
    lv_obj_set_height(ui_Panel51, LV_SIZE_CONTENT);    /// 10
    lv_obj_set_x(ui_Panel51, -320);
    lv_obj_set_y(ui_Panel51, -152);
    lv_obj_set_align(ui_Panel51, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel51, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel51, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel51, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel51, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel51, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel51, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel51, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel51, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel51, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Panel51, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Panel51, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label53 = lv_label_create(ui_Panel51);
    lv_obj_set_height(ui_Label53, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_flex_grow(ui_Label53, 1);
    lv_obj_set_align(ui_Label53, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label53, _("inv_volt_rms"));
    lv_label_set_recolor(ui_Label53, "true");
    lv_obj_set_style_text_font(ui_Label53, &ui_font_malgun20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblInvVoltRms = lv_label_create(ui_Panel51);
    lv_obj_set_width(ui_lblInvVoltRms, 50);
    lv_obj_set_height(ui_lblInvVoltRms, LV_SIZE_CONTENT);    /// 55
    lv_obj_set_align(ui_lblInvVoltRms, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblInvVoltRms, _("250"));
    lv_label_set_recolor(ui_lblInvVoltRms, "true");
    lv_obj_set_style_text_color(ui_lblInvVoltRms, lv_color_hex(0x1B15C6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblInvVoltRms, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblInvVoltRms, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblInvVoltRms, &ui_font_malgun20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblInvVoltRms, lv_color_hex(0xE6F0CF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblInvVoltRms, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel52 = lv_obj_create(ui_Container6);
    lv_obj_set_width(ui_Panel52, lv_pct(48));
    lv_obj_set_height(ui_Panel52, LV_SIZE_CONTENT);    /// 10
    lv_obj_set_x(ui_Panel52, -320);
    lv_obj_set_y(ui_Panel52, -152);
    lv_obj_set_align(ui_Panel52, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel52, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel52, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel52, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel52, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel52, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel52, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel52, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel52, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel52, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel52, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel52, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Panel52, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Panel52, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label54 = lv_label_create(ui_Panel52);
    lv_obj_set_height(ui_Label54, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_flex_grow(ui_Label54, 1);
    lv_obj_set_align(ui_Label54, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label54, _("inv_current_rms"));
    lv_label_set_recolor(ui_Label54, "true");
    lv_obj_set_style_text_font(ui_Label54, &ui_font_malgun20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Label54, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label54, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label54, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblInvCurrentRms = lv_label_create(ui_Panel52);
    lv_obj_set_width(ui_lblInvCurrentRms, 50);
    lv_obj_set_height(ui_lblInvCurrentRms, LV_SIZE_CONTENT);    /// 55
    lv_obj_set_align(ui_lblInvCurrentRms, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblInvCurrentRms, _("250"));
    lv_label_set_recolor(ui_lblInvCurrentRms, "true");
    lv_obj_set_style_text_color(ui_lblInvCurrentRms, lv_color_hex(0x1B15C6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblInvCurrentRms, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblInvCurrentRms, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblInvCurrentRms, &ui_font_malgun20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblInvCurrentRms, lv_color_hex(0xE6F0CF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblInvCurrentRms, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel53 = lv_obj_create(ui_Container6);
    lv_obj_set_width(ui_Panel53, lv_pct(48));
    lv_obj_set_height(ui_Panel53, LV_SIZE_CONTENT);    /// 10
    lv_obj_set_x(ui_Panel53, -320);
    lv_obj_set_y(ui_Panel53, -152);
    lv_obj_set_align(ui_Panel53, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel53, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel53, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel53, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel53, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel53, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel53, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel53, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel53, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel53, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Panel53, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Panel53, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Panel53, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel53, 1, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Label92 = lv_label_create(ui_Panel53);
    lv_obj_set_height(ui_Label92, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_flex_grow(ui_Label92, 1);
    lv_obj_set_align(ui_Label92, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label92, _("output_volt_rms"));
    lv_label_set_recolor(ui_Label92, "true");
    lv_obj_set_style_text_font(ui_Label92, &ui_font_malgun20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblOutputVoltRms = lv_label_create(ui_Panel53);
    lv_obj_set_width(ui_lblOutputVoltRms, 50);
    lv_obj_set_height(ui_lblOutputVoltRms, LV_SIZE_CONTENT);    /// 55
    lv_obj_set_align(ui_lblOutputVoltRms, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblOutputVoltRms, _("250"));
    lv_label_set_recolor(ui_lblOutputVoltRms, "true");
    lv_obj_set_style_text_color(ui_lblOutputVoltRms, lv_color_hex(0x1B15C6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblOutputVoltRms, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblOutputVoltRms, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblOutputVoltRms, &ui_font_malgun20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblOutputVoltRms, lv_color_hex(0xE6F0CF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblOutputVoltRms, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TapPage3 = lv_tabview_add_tab(ui_TabView3, "MEASURE");
    lv_obj_set_flex_flow(ui_TapPage3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_TapPage3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_pad_left(ui_TapPage3, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TapPage3, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TapPage3, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TapPage3, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TapPage3, &ui_font_malgun14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container3 = lv_obj_create(ui_TapPage3);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, lv_pct(100));
    lv_obj_set_height(ui_Container3, lv_pct(78));
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container3, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Container3, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_SPACE_EVENLY);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Container3, lv_color_hex(0xF8F4F4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Container3, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel44 = lv_obj_create(ui_Container3);
    lv_obj_set_width(ui_Panel44, lv_pct(48));
    lv_obj_set_height(ui_Panel44, LV_SIZE_CONTENT);    /// 10
    lv_obj_set_x(ui_Panel44, -320);
    lv_obj_set_y(ui_Panel44, -152);
    lv_obj_set_align(ui_Panel44, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel44, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel44, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel44, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel44, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel44, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel44, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel44, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel44, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel44, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel44, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel44, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel44, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Panel44, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Panel44, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label83 = lv_label_create(ui_Panel44);
    lv_obj_set_height(ui_Label83, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_flex_grow(ui_Label83, 1);
    lv_obj_set_align(ui_Label83, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label83, _("output_curr_rms"));
    lv_label_set_recolor(ui_Label83, "true");
    lv_obj_set_style_text_font(ui_Label83, &ui_font_malgun20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblOutputCurrRms = lv_label_create(ui_Panel44);
    lv_obj_set_width(ui_lblOutputCurrRms, 50);
    lv_obj_set_height(ui_lblOutputCurrRms, LV_SIZE_CONTENT);    /// 55
    lv_obj_set_align(ui_lblOutputCurrRms, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblOutputCurrRms, _("250"));
    lv_label_set_recolor(ui_lblOutputCurrRms, "true");
    lv_obj_set_style_text_color(ui_lblOutputCurrRms, lv_color_hex(0x1B15C6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblOutputCurrRms, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblOutputCurrRms, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblOutputCurrRms, &ui_font_malgun20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblOutputCurrRms, lv_color_hex(0xE6F0CF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblOutputCurrRms, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel45 = lv_obj_create(ui_Container3);
    lv_obj_set_width(ui_Panel45, lv_pct(48));
    lv_obj_set_height(ui_Panel45, LV_SIZE_CONTENT);    /// 10
    lv_obj_set_x(ui_Panel45, -320);
    lv_obj_set_y(ui_Panel45, -152);
    lv_obj_set_align(ui_Panel45, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel45, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel45, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel45, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel45, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel45, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel45, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel45, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel45, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel45, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel45, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel45, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Panel45, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Panel45, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label85 = lv_label_create(ui_Panel45);
    lv_obj_set_height(ui_Label85, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_flex_grow(ui_Label85, 1);
    lv_obj_set_align(ui_Label85, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label85, _("input_freqency"));
    lv_label_set_recolor(ui_Label85, "true");
    lv_obj_set_style_text_font(ui_Label85, &ui_font_malgun20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Label85, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label85, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label85, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblInputFreq = lv_label_create(ui_Panel45);
    lv_obj_set_width(ui_lblInputFreq, 50);
    lv_obj_set_height(ui_lblInputFreq, LV_SIZE_CONTENT);    /// 55
    lv_obj_set_align(ui_lblInputFreq, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblInputFreq, _("250"));
    lv_label_set_recolor(ui_lblInputFreq, "true");
    lv_obj_set_style_text_color(ui_lblInputFreq, lv_color_hex(0x1B15C6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblInputFreq, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblInputFreq, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblInputFreq, &ui_font_malgun20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblInputFreq, lv_color_hex(0xE6F0CF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblInputFreq, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel46 = lv_obj_create(ui_Container3);
    lv_obj_set_width(ui_Panel46, lv_pct(48));
    lv_obj_set_height(ui_Panel46, LV_SIZE_CONTENT);    /// 10
    lv_obj_set_x(ui_Panel46, -320);
    lv_obj_set_y(ui_Panel46, -152);
    lv_obj_set_align(ui_Panel46, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel46, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel46, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel46, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel46, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel46, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel46, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel46, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel46, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel46, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel46, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel46, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Panel46, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Panel46, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label87 = lv_label_create(ui_Panel46);
    lv_obj_set_height(ui_Label87, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_flex_grow(ui_Label87, 1);
    lv_obj_set_align(ui_Label87, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label87, _("inv_freqency"));
    lv_label_set_recolor(ui_Label87, "true");
    lv_obj_set_style_text_font(ui_Label87, &ui_font_malgun20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Label87, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label87, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label87, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblInvFreq = lv_label_create(ui_Panel46);
    lv_obj_set_width(ui_lblInvFreq, 50);
    lv_obj_set_height(ui_lblInvFreq, LV_SIZE_CONTENT);    /// 55
    lv_obj_set_align(ui_lblInvFreq, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblInvFreq, _("250"));
    lv_label_set_recolor(ui_lblInvFreq, "true");
    lv_obj_set_style_text_color(ui_lblInvFreq, lv_color_hex(0x1B15C6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblInvFreq, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblInvFreq, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblInvFreq, &ui_font_malgun20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblInvFreq, lv_color_hex(0xE6F0CF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblInvFreq, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel47 = lv_obj_create(ui_Container3);
    lv_obj_set_width(ui_Panel47, lv_pct(48));
    lv_obj_set_height(ui_Panel47, LV_SIZE_CONTENT);    /// 10
    lv_obj_set_x(ui_Panel47, -320);
    lv_obj_set_y(ui_Panel47, -152);
    lv_obj_set_align(ui_Panel47, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel47, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel47, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel47, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel47, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel47, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel47, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel47, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel47, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel47, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel47, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel47, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Panel47, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Panel47, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label89 = lv_label_create(ui_Panel47);
    lv_obj_set_height(ui_Label89, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_flex_grow(ui_Label89, 1);
    lv_obj_set_align(ui_Label89, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label89, _("bypass_freqency"));
    lv_label_set_recolor(ui_Label89, "true");
    lv_obj_set_style_text_font(ui_Label89, &ui_font_malgun20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Label89, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label89, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label89, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblBypassFreq = lv_label_create(ui_Panel47);
    lv_obj_set_width(ui_lblBypassFreq, 50);
    lv_obj_set_height(ui_lblBypassFreq, LV_SIZE_CONTENT);    /// 55
    lv_obj_set_align(ui_lblBypassFreq, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblBypassFreq, _("250"));
    lv_label_set_recolor(ui_lblBypassFreq, "true");
    lv_obj_set_style_text_color(ui_lblBypassFreq, lv_color_hex(0x1B15C6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblBypassFreq, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblBypassFreq, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblBypassFreq, &ui_font_malgun20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblBypassFreq, lv_color_hex(0xE6F0CF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblBypassFreq, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel60 = lv_obj_create(ui_Container3);
    lv_obj_set_width(ui_Panel60, lv_pct(48));
    lv_obj_set_height(ui_Panel60, LV_SIZE_CONTENT);    /// 10
    lv_obj_set_x(ui_Panel60, -320);
    lv_obj_set_y(ui_Panel60, -152);
    lv_obj_set_align(ui_Panel60, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel60, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel60, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel60, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel60, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel60, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel60, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel60, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel60, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel60, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel60, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel60, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Panel60, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Panel60, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label91 = lv_label_create(ui_Panel60);
    lv_obj_set_height(ui_Label91, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_flex_grow(ui_Label91, 1);
    lv_obj_set_align(ui_Label91, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label91, _("Battery_Capacity"));
    lv_label_set_recolor(ui_Label91, "true");
    lv_obj_set_style_text_font(ui_Label91, &ui_font_malgun20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Label91, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label91, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label91, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblBattCapacity = lv_label_create(ui_Panel60);
    lv_obj_set_width(ui_lblBattCapacity, 50);
    lv_obj_set_height(ui_lblBattCapacity, LV_SIZE_CONTENT);    /// 55
    lv_obj_set_align(ui_lblBattCapacity, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblBattCapacity, _("250"));
    lv_label_set_recolor(ui_lblBattCapacity, "true");
    lv_obj_set_style_text_color(ui_lblBattCapacity, lv_color_hex(0x1B15C6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblBattCapacity, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblBattCapacity, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblBattCapacity, &ui_font_malgun20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblBattCapacity, lv_color_hex(0xE6F0CF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblBattCapacity, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel62 = lv_obj_create(ui_Container3);
    lv_obj_set_width(ui_Panel62, lv_pct(48));
    lv_obj_set_height(ui_Panel62, LV_SIZE_CONTENT);    /// 10
    lv_obj_set_x(ui_Panel62, -320);
    lv_obj_set_y(ui_Panel62, -152);
    lv_obj_set_align(ui_Panel62, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel62, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel62, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel62, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel62, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel62, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel62, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel62, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel62, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel62, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel62, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel62, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Panel62, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Panel62, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label128 = lv_label_create(ui_Panel62);
    lv_obj_set_height(ui_Label128, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_flex_grow(ui_Label128, 1);
    lv_obj_set_align(ui_Label128, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label128, _("UPS_Inner_Temp"));
    lv_label_set_recolor(ui_Label128, "true");
    lv_obj_set_style_text_font(ui_Label128, &ui_font_malgun20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Label128, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label128, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label128, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblUpsInnerTemp = lv_label_create(ui_Panel62);
    lv_obj_set_width(ui_lblUpsInnerTemp, 50);
    lv_obj_set_height(ui_lblUpsInnerTemp, LV_SIZE_CONTENT);    /// 55
    lv_obj_set_align(ui_lblUpsInnerTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblUpsInnerTemp, _("250"));
    lv_label_set_recolor(ui_lblUpsInnerTemp, "true");
    lv_obj_set_style_text_color(ui_lblUpsInnerTemp, lv_color_hex(0x1B15C6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblUpsInnerTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblUpsInnerTemp, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblUpsInnerTemp, &ui_font_malgun20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblUpsInnerTemp, lv_color_hex(0xE6F0CF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblUpsInnerTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabPage5 = lv_tabview_add_tab(ui_TabView3, "GainView");
    lv_obj_set_flex_flow(ui_TabPage5, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_TabPage5, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_pad_left(ui_TabPage5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TabPage5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TabPage5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TabPage5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_TabPage5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_TabPage5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TabPage5, &ui_font_malgun20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container8 = lv_obj_create(ui_TabPage5);
    lv_obj_remove_style_all(ui_Container8);
    lv_obj_set_width(ui_Container8, lv_pct(100));
    lv_obj_set_height(ui_Container8, lv_pct(78));
    lv_obj_set_align(ui_Container8, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container8, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Container8, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_SPACE_EVENLY);
    lv_obj_clear_flag(ui_Container8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel68 = lv_obj_create(ui_Container8);
    lv_obj_set_width(ui_Panel68, lv_pct(48));
    lv_obj_set_height(ui_Panel68, LV_SIZE_CONTENT);    /// 10
    lv_obj_set_x(ui_Panel68, -320);
    lv_obj_set_y(ui_Panel68, -152);
    lv_obj_set_align(ui_Panel68, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel68, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel68, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel68, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel68, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel68, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel68, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel68, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel68, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel68, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel68, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel68, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel68, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Panel68, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Panel68, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label102 = lv_label_create(ui_Panel68);
    lv_obj_set_height(ui_Label102, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_flex_grow(ui_Label102, 1);
    lv_obj_set_align(ui_Label102, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label102, _("Input_volt_gain"));
    lv_label_set_recolor(ui_Label102, "true");

    ui_lblInputVoltGain = lv_label_create(ui_Panel68);
    lv_obj_set_width(ui_lblInputVoltGain, 50);
    lv_obj_set_height(ui_lblInputVoltGain, LV_SIZE_CONTENT);    /// 55
    lv_obj_set_align(ui_lblInputVoltGain, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblInputVoltGain, _("250"));
    lv_label_set_recolor(ui_lblInputVoltGain, "true");
    lv_obj_set_style_text_color(ui_lblInputVoltGain, lv_color_hex(0x1B15C6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblInputVoltGain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblInputVoltGain, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblInputVoltGain, lv_color_hex(0xE6F0CF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblInputVoltGain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel69 = lv_obj_create(ui_Container8);
    lv_obj_set_width(ui_Panel69, lv_pct(48));
    lv_obj_set_height(ui_Panel69, LV_SIZE_CONTENT);    /// 10
    lv_obj_set_x(ui_Panel69, -320);
    lv_obj_set_y(ui_Panel69, -152);
    lv_obj_set_align(ui_Panel69, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel69, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel69, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel69, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel69, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel69, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel69, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel69, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel69, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel69, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel69, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel69, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel69, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Panel69, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Panel69, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label104 = lv_label_create(ui_Panel69);
    lv_obj_set_height(ui_Label104, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_flex_grow(ui_Label104, 1);
    lv_obj_set_align(ui_Label104, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label104, _("input_curr_gain"));
    lv_label_set_recolor(ui_Label104, "true");

    ui_lblInputCurrGain = lv_label_create(ui_Panel69);
    lv_obj_set_width(ui_lblInputCurrGain, 50);
    lv_obj_set_height(ui_lblInputCurrGain, LV_SIZE_CONTENT);    /// 55
    lv_obj_set_align(ui_lblInputCurrGain, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblInputCurrGain, _("250"));
    lv_label_set_recolor(ui_lblInputCurrGain, "true");
    lv_obj_set_style_text_color(ui_lblInputCurrGain, lv_color_hex(0x1B15C6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblInputCurrGain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblInputCurrGain, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblInputCurrGain, lv_color_hex(0xE6F0CF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblInputCurrGain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel70 = lv_obj_create(ui_Container8);
    lv_obj_set_width(ui_Panel70, lv_pct(48));
    lv_obj_set_height(ui_Panel70, LV_SIZE_CONTENT);    /// 10
    lv_obj_set_x(ui_Panel70, -320);
    lv_obj_set_y(ui_Panel70, -152);
    lv_obj_set_align(ui_Panel70, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel70, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel70, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel70, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel70, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel70, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel70, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel70, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel70, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel70, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel70, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel70, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel70, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Panel70, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Panel70, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label106 = lv_label_create(ui_Panel70);
    lv_obj_set_height(ui_Label106, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_flex_grow(ui_Label106, 1);
    lv_obj_set_align(ui_Label106, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label106, _("vdc_link_volt_gain"));
    lv_label_set_recolor(ui_Label106, "true");

    ui_lblVdcLinkVoltGain = lv_label_create(ui_Panel70);
    lv_obj_set_width(ui_lblVdcLinkVoltGain, 50);
    lv_obj_set_height(ui_lblVdcLinkVoltGain, LV_SIZE_CONTENT);    /// 55
    lv_obj_set_align(ui_lblVdcLinkVoltGain, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblVdcLinkVoltGain, _("250"));
    lv_label_set_recolor(ui_lblVdcLinkVoltGain, "true");
    lv_obj_set_style_text_color(ui_lblVdcLinkVoltGain, lv_color_hex(0x1B15C6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblVdcLinkVoltGain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblVdcLinkVoltGain, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblVdcLinkVoltGain, lv_color_hex(0xE6F0CF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblVdcLinkVoltGain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel71 = lv_obj_create(ui_Container8);
    lv_obj_set_width(ui_Panel71, lv_pct(48));
    lv_obj_set_height(ui_Panel71, LV_SIZE_CONTENT);    /// 10
    lv_obj_set_x(ui_Panel71, -320);
    lv_obj_set_y(ui_Panel71, -152);
    lv_obj_set_align(ui_Panel71, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel71, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel71, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel71, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel71, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel71, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel71, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel71, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel71, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel71, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel71, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel71, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel71, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Panel71, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Panel71, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label108 = lv_label_create(ui_Panel71);
    lv_obj_set_height(ui_Label108, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_flex_grow(ui_Label108, 1);
    lv_obj_set_align(ui_Label108, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label108, _("vbat_volt_gain"));
    lv_label_set_recolor(ui_Label108, "true");

    ui_lblVbatVoltGain = lv_label_create(ui_Panel71);
    lv_obj_set_width(ui_lblVbatVoltGain, 50);
    lv_obj_set_height(ui_lblVbatVoltGain, LV_SIZE_CONTENT);    /// 55
    lv_obj_set_align(ui_lblVbatVoltGain, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblVbatVoltGain, _("250"));
    lv_label_set_recolor(ui_lblVbatVoltGain, "true");
    lv_obj_set_style_text_color(ui_lblVbatVoltGain, lv_color_hex(0x1B15C6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblVbatVoltGain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblVbatVoltGain, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblVbatVoltGain, lv_color_hex(0xE6F0CF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblVbatVoltGain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel72 = lv_obj_create(ui_Container8);
    lv_obj_set_width(ui_Panel72, lv_pct(48));
    lv_obj_set_height(ui_Panel72, LV_SIZE_CONTENT);    /// 10
    lv_obj_set_x(ui_Panel72, -320);
    lv_obj_set_y(ui_Panel72, -152);
    lv_obj_set_align(ui_Panel72, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel72, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel72, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel72, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel72, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel72, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel72, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel72, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel72, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel72, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel72, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel72, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel72, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Panel72, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Panel72, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label110 = lv_label_create(ui_Panel72);
    lv_obj_set_height(ui_Label110, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_flex_grow(ui_Label110, 1);
    lv_obj_set_align(ui_Label110, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label110, _("bat_current_gain"));
    lv_label_set_recolor(ui_Label110, "true");

    ui_lblBatCurrentGain = lv_label_create(ui_Panel72);
    lv_obj_set_width(ui_lblBatCurrentGain, 50);
    lv_obj_set_height(ui_lblBatCurrentGain, LV_SIZE_CONTENT);    /// 55
    lv_obj_set_align(ui_lblBatCurrentGain, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblBatCurrentGain, _("250"));
    lv_label_set_recolor(ui_lblBatCurrentGain, "true");
    lv_obj_set_style_text_color(ui_lblBatCurrentGain, lv_color_hex(0x1B15C6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblBatCurrentGain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblBatCurrentGain, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblBatCurrentGain, lv_color_hex(0xE6F0CF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblBatCurrentGain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel73 = lv_obj_create(ui_Container8);
    lv_obj_set_width(ui_Panel73, lv_pct(48));
    lv_obj_set_height(ui_Panel73, LV_SIZE_CONTENT);    /// 10
    lv_obj_set_x(ui_Panel73, -321);
    lv_obj_set_y(ui_Panel73, -152);
    lv_obj_set_align(ui_Panel73, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel73, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel73, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel73, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel73, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel73, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel73, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel73, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel73, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel73, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel73, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel73, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel73, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Panel73, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Panel73, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label112 = lv_label_create(ui_Panel73);
    lv_obj_set_height(ui_Label112, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_flex_grow(ui_Label112, 1);
    lv_obj_set_align(ui_Label112, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label112, _("inverter_volt_gain"));
    lv_label_set_recolor(ui_Label112, "true");

    ui_lblInverterVoltGain = lv_label_create(ui_Panel73);
    lv_obj_set_width(ui_lblInverterVoltGain, 50);
    lv_obj_set_height(ui_lblInverterVoltGain, LV_SIZE_CONTENT);    /// 55
    lv_obj_set_align(ui_lblInverterVoltGain, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblInverterVoltGain, _("250"));
    lv_label_set_recolor(ui_lblInverterVoltGain, "true");
    lv_obj_set_style_text_color(ui_lblInverterVoltGain, lv_color_hex(0x1B15C6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblInverterVoltGain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblInverterVoltGain, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblInverterVoltGain, lv_color_hex(0xE6F0CF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblInverterVoltGain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel74 = lv_obj_create(ui_Container8);
    lv_obj_set_width(ui_Panel74, lv_pct(48));
    lv_obj_set_height(ui_Panel74, LV_SIZE_CONTENT);    /// 10
    lv_obj_set_x(ui_Panel74, -321);
    lv_obj_set_y(ui_Panel74, -152);
    lv_obj_set_align(ui_Panel74, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel74, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel74, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel74, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel74, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel74, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel74, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel74, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel74, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel74, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel74, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel74, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel74, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Panel74, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Panel74, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label114 = lv_label_create(ui_Panel74);
    lv_obj_set_height(ui_Label114, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_flex_grow(ui_Label114, 1);
    lv_obj_set_align(ui_Label114, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_Label114, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_Label114, _("inverter_curr_gain"));
    lv_label_set_recolor(ui_Label114, "true");

    ui_lblInvCurrGain = lv_label_create(ui_Panel74);
    lv_obj_set_width(ui_lblInvCurrGain, 50);
    lv_obj_set_height(ui_lblInvCurrGain, LV_SIZE_CONTENT);    /// 55
    lv_obj_set_align(ui_lblInvCurrGain, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblInvCurrGain, _("250"));
    lv_label_set_recolor(ui_lblInvCurrGain, "true");
    lv_obj_set_style_text_color(ui_lblInvCurrGain, lv_color_hex(0x1B15C6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblInvCurrGain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblInvCurrGain, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblInvCurrGain, lv_color_hex(0xE6F0CF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblInvCurrGain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel75 = lv_obj_create(ui_Container8);
    lv_obj_set_width(ui_Panel75, lv_pct(48));
    lv_obj_set_height(ui_Panel75, LV_SIZE_CONTENT);    /// 10
    lv_obj_set_x(ui_Panel75, -321);
    lv_obj_set_y(ui_Panel75, -152);
    lv_obj_set_align(ui_Panel75, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel75, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel75, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel75, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel75, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel75, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel75, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel75, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel75, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel75, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel75, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel75, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel75, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Panel75, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Panel75, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label116 = lv_label_create(ui_Panel75);
    lv_obj_set_height(ui_Label116, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_flex_grow(ui_Label116, 1);
    lv_obj_set_align(ui_Label116, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label116, _("output_curr_gain"));
    lv_label_set_recolor(ui_Label116, "true");

    ui_lblOutputCurrGain = lv_label_create(ui_Panel75);
    lv_obj_set_width(ui_lblOutputCurrGain, 50);
    lv_obj_set_height(ui_lblOutputCurrGain, LV_SIZE_CONTENT);    /// 55
    lv_obj_set_align(ui_lblOutputCurrGain, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblOutputCurrGain, _("250"));
    lv_label_set_recolor(ui_lblOutputCurrGain, "true");
    lv_obj_set_style_text_color(ui_lblOutputCurrGain, lv_color_hex(0x1B15C6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblOutputCurrGain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblOutputCurrGain, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblOutputCurrGain, lv_color_hex(0xE6F0CF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblOutputCurrGain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button10 = lv_btn_create(ui_TabView3);
    lv_obj_set_height(ui_Button10, 40);
    lv_obj_set_width(ui_Button10, lv_pct(30));
    lv_obj_set_x(ui_Button10, -4);
    lv_obj_set_y(ui_Button10, 227);
    lv_obj_set_align(ui_Button10, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_flex_flow(ui_Button10, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Button10, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button10, LV_OBJ_FLAG_IGNORE_LAYOUT | LV_OBJ_FLAG_FLOATING |
                    LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button10, lv_color_hex(0xF06418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Button10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Button10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Button10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Button10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Button10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Button10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label123 = lv_label_create(ui_Button10);
    lv_obj_set_width(ui_Label123, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label123, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label123, -5);
    lv_obj_set_y(ui_Label123, 0);
    lv_obj_set_align(ui_Label123, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Label123, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Label123, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_label_set_text(ui_Label123, _("Back"));
    lv_obj_set_style_text_align(ui_Label123, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label123, &ui_font_malgun20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button10, ui_event_Button10, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_scrMeasure, ui_event_scrMeasure, LV_EVENT_ALL, NULL);

}
