// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.3
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void btnAlarmRunStop(lv_event_t * e);
void scrSettingScreenLoaded(lv_event_t * e);
void evtTabUpsSetup(lv_event_t * e);
void EventTxtBatVolSet(lv_event_t * e);
void EventTxtBatCurrset(lv_event_t * e);
void EventTxtOutputVolSet(lv_event_t * e);
void hfModeValueChangedEvent(lv_event_t * e);
void TabEventSetupVolClick(lv_event_t * e);
void TabEventSetupTimeClick(lv_event_t * e);
void evtTabGainSetup1(lv_event_t * e);
void EventTxtInputVoltGain(lv_event_t * e);
void EventTxtInputCurrGain(lv_event_t * e);
void EventTxtInvVoltGain(lv_event_t * e);
void EventTxtInvCurrGain(lv_event_t * e);
void TabEvtNextClick(lv_event_t * e);
void TabEvtOffsetClick(lv_event_t * e);
void TabEvtESCClick(lv_event_t * e);
void EventTxtVbatVoltGain(lv_event_t * e);
void EventTxtBatCurrGain(lv_event_t * e);
void EventTxtOutputCurrGain(lv_event_t * e);
void EventTxtInputVdcLinkGain(lv_event_t * e);
void TabEvtPrevClick(lv_event_t * e);
void evtTabGainSetup2(lv_event_t * e);
void evtSystemTabClicked(lv_event_t * e);
void EventTxtYear(lv_event_t * e);
void EventTxtMonth(lv_event_t * e);
void EventTxtDay(lv_event_t * e);
void EventTxtHour(lv_event_t * e);
void EventTxtMinute(lv_event_t * e);
void EventTxtSecond(lv_event_t * e);
void ChangeLanguage(lv_event_t * e);
void EventTxtOfftime(lv_event_t * e);
void EventTxtBrigtness(lv_event_t * e);
void keyBoardValueChangedEvent(lv_event_t * e);
void evtMessageLblClick(lv_event_t * e);
void btnEventRunUps(lv_event_t * e);
void btnEventStopUps(lv_event_t * e);
void scrMeasureLoadEvent(lv_event_t * e);
void evtLogScreenLoaded(lv_event_t * e);
void btnAlarmRunStopAtLog(lv_event_t * e);
void EventLogPrev(lv_event_t * e);
void EventLogNext(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
