// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.3
// Project name: SquareLine_Project

#include "ui.h"
#include "main.h"
#include <EEPROM.h>
#include "lv_i18n.h"

extern nvsSystemSet ipAddress_struct;
void ChangeLanguage(lv_event_t * e)
{
	if(strcmp("ko-KR", lv_i18n_get_current_locale()) == 0 )
    	lv_i18n_set_locale("en-GB");
    else 	
		lv_i18n_set_locale("ko-KR");
    ui_init();
	
    //lv_i18n_set_locale("en-GB");
	// Your code here
}

void btnEvnetSaveSetting(lv_event_t * e)
{
	ipAddress_struct.bright = lv_slider_get_value(ui_SliderBrightness);
	Serial.printf("\nSet Brigtness is %d", ipAddress_struct.bright);
	ledcWrite(0, ipAddress_struct.bright);
	ipAddress_struct.LED_OFF_TIME = lv_slider_get_value(ui_SliderLedOffTime);

	tm nowTime;
	nowTime.tm_year = String(lv_label_get_text(ui_lblYearSet)).toInt() - 1900;
	nowTime.tm_mon = String(lv_label_get_text(ui_lblMonthSet)).toInt();
	nowTime.tm_mday = String(lv_label_get_text(ui_lblDaySet)).toInt();
	nowTime.tm_hour = String(lv_label_get_text(ui_lblSetHour)).toInt();
	nowTime.tm_min = String(lv_label_get_text(ui_lblSetMinute)).toInt();
	nowTime.tm_sec = String(lv_label_get_text(ui_lblSetSecond)).toInt();
  	time_t now = mktime(&nowTime);
	timeval tVal;
	tVal.tv_sec = now;
	settimeofday(&tVal,NULL);

	EEPROM.writeBytes(1, (const byte *)&ipAddress_struct, sizeof(nvsSystemSet));
	EEPROM.commit();
}

void btnEventRunUps(lv_event_t * e)
{
	// Your code here
}

void btnEventStopUps(lv_event_t * e)
{
	// Your code here
}
